services:
  - type: web
    name: proyecto-j-streamlit
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app_simple.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DISPLAY
        value: ":99"
    healthCheckPath: / 