name: proyecto_j
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - statsmodels
  - missingno
  - openpyxl
  - xlrd
  - pyreadstat
  - fpdf2
  - defusedxml
  - svg.path
  - jupyter
  - notebook
  - ipykernel
  - pytest
  - flake8
  - black
  - pip
  - pip:
      - streamlit
      - pyarrow
      - pydeck
      - narwhals
      - attrs
      - blinker
      - cachetools
      - certifi
      - charset-normalizer
      - click
      - colorama
      - contourpy
      - cycler
      - fonttools
      - gitdb
      - GitPython
      - idna
      - Jinja2
      - jsonschema
      - jsonschema-specifications
      - kiwisolver
      - MarkupSafe
      - packaging
      - pillow
      - protobuf
      - pyparsing
      - python-dateutil
      - pytz
      - referencing
      - requests
      - rpds-py
      - six
      - smmap
      - tenacity
      - toml
      - tornado
      - typing_extensions
      - tzdata
      - urllib3
      - watchdog
      - pytest-cov
      - pytest-mock 